.Dd $Mdocdate$
.Dt TREE 1
.Os
.Sh NAME
.Nm tree
.Nd tree listing of filesystem paths.
.Sh SYNOPSIS
.Nm tree
.Op Fl Aacghilmnoprs
.Op Ar path Cm ...
.Sh DESCRIPTION
The
.Nm
prints a listing of files as a tree, using box drawing characters
from the UTF set, or the ASCII characters
.Cm '-' ,
.Cm '+' ,
.Cm '`'
and
.Cm '|' .
The program also can include the fields of a long listing
directory (as option
.Cm Fl l
of
.Cm ls
command does)
The field are printed depending on the options used, but they are
ordered in the same positions they appear int the long
.Cm ls
listing.
This is
.Bl -tag
.It inode
The inode number is printed using a 9 character field (to
maintain the alignment so the tree doesn't get garbled)
.It permissions
The permissions, as they appear in the
.Cm ls
command.
.It links
The number of hard links pointing to the file/directory inode.
.It user
The user name is printed (or if the option
.Fl n
is used, only the user id number)
.It group
The group name (or the gid number if the option
.Fl n
is used)
printed)
.It size
The size of the file in bytes.
.It last modification timestamp
The time of the last modification.
.It last access timestmp
The time of last access.
.It last inode change
The time of the last inode change.
.It the file name
This is always printed.
.El
.Sh OPTIONS
.Bl -tag
.It Fl A
This option toggles the switch between using utf-8 box drawing
characters and ASCII characters.
Default is utf-8.
.It Fl a
This option toggles the inclusion of the last access time of the
file in the listing.
.It Fl c
This option toggles the inclusion of the last inode modification
to the file in the listing.
.It Fl g
This option toggles the inclusion of the group name of the file
to the file in the listing.
.It Fl h
This option toggles the display of the help screen.
.It Fl i
This option toggles the inclusion of the i-node number of the
file in the listing.
.It Fl l
This option toggles the inclusion of the number of links pointing
to this inode in the listing.
.It Fl m
This option toggles the inclusion of the last modification time
of the file in the listing.
.It Fl n
This option toggles numerical output (for user id and group id)
of the file in the listing.
.It Fl o
This option toggles the inclusion of the owner of the file in the
listing.
.It Fl p
This option toggles the inclusion of the permissions field in the
listing.
.It Fl r
This option toggles the sorting in reverse collation order of the
files in the listing.
.It Fl s
This option toggles the inclusion of the size field in the
listing.
.El
.Sh AUTHOR
.An "Luis Colorado" Aq Mt luiscoloradourcola@gmail.com
